[build]
  command = "npm run build"
  publish = "dist"
  
[dev]
  command = "npm run dev"
  port = 5173
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Main SPA catch-all route - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  
# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://smooth-sunburst-123456.netlify.app/:splat"
  status = 301
  force = true
  
# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true
  
# Custom redirects (add your specific routes here)
# Example:
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301
